apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-web1-deployment
  labels:
    app : my-k8s1-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      project: kgb1
  template:
    metadata:
      labels:
        project: kgb1   # Service will look for those PODS Labels!!!
    spec:
      containers:
        - name : kgb-web1
          image: pva2008/k8sphp:version1
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 56Mi
              cpu: "0.1"