apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-hosts

spec:
  rules:
  - host: www.s5.zzz
    http:
      paths:
        - backend:
           serviceName: main
           servicePort: 80

  - host: www.s6.zzz
    http:
      paths:
        - backend:
           serviceName: web1
           servicePort: 80

  - host: wwww.s7.zzz
    http:
      paths:
        - backend:
           serviceName: web2
           servicePort: 80

  - host: www.cat.zzz
    http:
      paths:
        - backend:
           serviceName: tomcat
           servicePort: 8080
